version: "3"

services:

    mysql:
        container_name: mysqldatabase
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          MYSQL_DATABASE: 'api-fruits'
          MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - "3306:3306"
            